Upgrading node version in sonar build pipeline
Upgrading node version to 16 in sonar build pipeline. Fix for build issue:
Error: Cannot find module 'node:os'
Require stack:
- /home/runner/work/insomnia-plugin-mastercard/insomnia-plugin-mastercard/node_modules/mocha/bin/mocha.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:962:15)
    at Function.Module._load (internal/modules/cjs/loader.js:838:27)
    at Module.require (internal/modules/cjs/loader.js:1022:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/home/runner/work/insomnia-plugin-mastercard/insomnia-plugin-mastercard/node_modules/mocha/bin/mocha.js:13:12)
    at Module._compile (internal/modules/cjs/loader.js:1118:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1138:10)
    at Module.load (internal/modules/cjs/loader.js:982:32)
    at Function.Module._load (internal/modules/cjs/loader.js:875:14)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:71:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/insomnia-plugin-mastercard/insomnia-plugin-mastercard/node_modules/mocha/bin/mocha.js'
  ]
}